---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
  namespace: default
data:
  EULA: "TRUE"
  MOTD: "Nathaniel White's Minecraft Server"
  VERSION: "1.21.11"
  MEMORY: "2G"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: 238039006137.dkr.ecr.us-east-1.amazonaws.com/minecraft-server:mc-1.21.11-build2
          ports:
            - containerPort: 25565
          envFrom:
            - configMapRef:
                name: minecraft-config
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "1500m"
          startupProbe:
            tcpSocket:
              port: 25565
            failureThreshold: 36
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-data

---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565